name: Node.js Continuous Integration

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  node-test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node: [16.x]

    steps:
      - name: Setup NodeJs ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Yarn Install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Prettier Format Check Test
        run: yarn format:check

      - name: ESLint Error Only Test
        run: yarn lint:error

      - name: TypeScript Test
        run: yarn ts:test

      - name: Jest and DOM Test
        run: yarn test
